### ISSUE TITLE
It appears google has fully killed pre-polymer youtube

### ISSUE THREAD

**Issue by ilikenwf** [jhonatasrm/Fast-YouTube-Load#2]
I'm not sure if I should use invidious or if we can just implement our own frontend using the youtube APIS...

**Comment by extremMiSt** [comment]
yep it broke,
I know someone who uses invidious and it's also in a state of flux currently. YT heavily dislikes alternative front ends and regularly breaks them, which is a real hassle to deal with.

**Comment by jhonatasrm** [comment]
I'm not working with this add-on anymore (time issue) and I don't know any possible solution for that.. if u have any idea how we can proceed, let's discuss about.

:)

**Comment by TAbdiukov** [comment]
can confirm Youtube killed it, but maybe not for all user agents and/or regions?

**Comment by TAbdiukov** [comment]
UPDATE: Changing User-Agent to
```
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```
Seems to revert Youtube's video watching page (but not the landing page etc) to the classic design

**Comment by TAbdiukov** [comment]
Proof
![Screenshot_2020-08-06 On the Distinction Between Physicians and Scientists Academics (THE SAAD TRUTH_1108)](https://user-images.githubusercontent.com/18607514/89484968-0898c880-d7e3-11ea-83b9-55baad75c659.png)

@jhonatasrm jhonatasrm

**Comment by jhonatasrm** [comment]
> can confirm Youtube killed it, but maybe not for all user agents and/or regions?

Yes.. I think is a gradual update in the future will not work anymore.
😞
