### ISSUE TITLE
Remove the argument about Shadow DOM v0

### ISSUE THREAD

**Issue by saschanaz** [jhonatasrm/Fast-YouTube-Load#4]
Per https://chromestatus.com/feature/4507242028072960 it's removed from Chrome too, and that specific thing thus can't cause performance difference anymore.

**Comment by jhonatasrm** [comment]
Thank you very much @saschanaz! I'm not providing any updates for this add-on anymore.

**Comment by saschanaz** [comment]
Oh, in that case another way would be to archive this repo 👀
